### PR TITLE
Add "pyright.disableSelfClsNotAccessed" option

### LINKED ISSUE #381: Remove warning for 'self' not being accessed
`self` is always required in class method parameter, and it is perfectly normal to not use it at all.  
But coc-pyright always shows warning for not accessing self.  
I think it's completely unnecessary and should be removed.

### PR DESCRIPTION
**Pull request by yaegassy**
## Description

Added an option to suppress the Unnecessary code in DiagnosticTag.

close #381 #271 #85 and more?...

## Demo

coc-pyright-unnecessary

### CODE REVIEW

**Comment by fannheyward** [comment]
This do disabled the `self not being accessed`, but also removed the unused warning:

```
    def __init__(self, unused1: str):
        unused2 = 1
        pass
```

**Comment by yaegassy** [comment]
Thanks for the review.

I considered the idea of excluding the target message (`self`, `cls`), but...  Hmm.

```typescript
      handleDiagnostics: (uri: string, diagnostics: Diagnostic[], next: HandleDiagnosticsSignature) => {
        if (disableDiagnosticUnnecessaryTag) {
          diagnostics = diagnostics.filter((d) => d.message !== '"self" is not accessed');
          diagnostics = diagnostics.filter((d) => d.message !== '"cls" is not accessed');
        }
        next(uri, diagnostics);
      },
```

**Comment by fannheyward** [comment]
@yaegassy same idea, it's an _ugly-hard-code_, but it's ok. 😆

**Comment by yaegassy** [comment]
@fannheyward What do you think would be a good name for the option?

`pyright.disableDiagnosticUnnecessaryTag` -> `pyright.disableDiagnosticXXXX`

**Comment by fannheyward** [comment]
@yaegassy `pyright.disableSelfClsNotAccessed`, the more detailed the better.

**Review by fannheyward — APPROVED** [review]

**Comment by yaegassy** [comment]
@fannheyward PR has been adjusted.

If there is anything inadequate, sorry, but please correct it. 🙇

**Comment by fannheyward** [comment]
From Pyright 1.1.133, this may not needed. https://github.com/microsoft/pyright/commit/ce71890c19ece17f0b00482777acc4ca0b69e37d

> Behavior Change: Automatically mark parameters as accessed (so they don't appear as "grayed out") in the following circumstances: 1) it is a self parameter in an instance method, 2) it is a cls parameter in a class method, 3) it is a parameter in a method marked abstract, 4) it is a parameter in a method that is part of a protocol class, 5) it is a parameter in an overload signature.

**Comment by yaegassy** [comment]
I have checked in my environment, and `pyright.disableSelfClsNotAccessed` is not necessary after v1.1.33. 😇

**Pull request merged**
