### PR TITLE
fix(ruff): support new ruff fix format

### PR DESCRIPTION
**Pull request by fannheyward**
support old and new format both

close #916

### CODE REVIEW

**Comment by lithammer** [comment]
Hmm, I don't see `fix.message` being used anywhere. That's where the title of the fix is.

**Comment by fannheyward** [comment]
@lithammer yes, the `fix.message` didn't use

```
    "message": "`sys` imported but unused",
    "fix": {
      "message": "Remove unused import: `sys`",
```

The output.message is used.

**Comment by fannheyward** [comment]
VSCode + Ruff:

截屏2023-04-18 17 06 47

coc-pyright with ruff:

截屏2023-04-18 17 07 05

**Comment by fannheyward** [comment]
There're two things:

1. diagnostic message, shows in floating/virtualText, warning the code error, this should use `output.message`
2. codeAction message, or codeAction title, this should use `msg.message` for better human reading

For the first one, if we use `output.message`:

截屏2023-04-18 17 17 43

This is not good for diagnostic reporting.

**Comment by fannheyward** [comment]
截屏2023-04-18 18 14 16

截屏2023-04-18 18 14 28

**Pull request merged**
